[build]
    command = "# no build command"
    functions = "netlify/functions"
    publish = "public"


[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
